using System;
using System.Data;
using System.Windows.Forms;
using System.Data.SqlClient;
using DevExpress.Xpo;
using DevExpress.Utils;
using DevExpress.ExpressApp;
using DevExpress.XtraEditors;
using DevExpress.XtraPivotGrid;
using DevExpress.ExpressApp.Xpo;
using DevExpress.ExpressApp.Editors;
using EcoplastERP.Module.BusinessObjects.ProductionObjects;

namespace EcoplastERP.Module.Win.UserForms
{
    public partial class MachineCapacityTargetReportUserControl : XtraUserControl, IComplexControl
    {
        public MachineCapacityTargetReportUserControl()
        {
            InitializeComponent();
        }

        private XafApplication application;
        private IObjectSpace objectSpace;

        void IComplexControl.Setup(IObjectSpace objectSpace, XafApplication application)
        {
            this.application = application;
            this.objectSpace = objectSpace;
        }

        private void MachineCapacityTargetReportUserControl_Load(object sender, EventArgs e)
        {
            txtYear.Text = DateTime.Now.Year.ToString();
            txtMonth.Text = DateTime.Now.Month.ToString();

            cbCapacityGroup.Properties.DataSource = new XPCollection<CapacityGroup>(((XPObjectSpace)objectSpace).Session, null, new SortProperty("Name", DevExpress.Xpo.DB.SortingDirection.Ascending));
            cbCapacityGroup.Properties.DisplayMember = "Name";
            cbCapacityGroup.Properties.ValueMember = "Oid";

            cbFilmKind.Properties.DataSource = new XPCollection<FilmKind>(((XPObjectSpace)objectSpace).Session, null, new SortProperty("Name", DevExpress.Xpo.DB.SortingDirection.Ascending));
            cbFilmKind.Properties.DisplayMember = "Name";
            cbFilmKind.Properties.ValueMember = "Oid";
        }

        public void RefreshGrid()
        {
            Cursor.Current = Cursors.WaitCursor;
            DataTable dt = new DataTable();
            gridControl1.DataSource = null;
            gridView1.Columns.Clear();
            string select = string.Empty, where = string.Empty, orderby = string.Empty;

            select = string.Format(@"declare @year int, @month int, @lastmonthfirstday date, @lastmonthlastday date, @firstday date, @lastday date 
set @year = {0}	set @month = {1}	
select @lastmonthfirstday = dateadd(month, datediff(month, 0, cast(@year as nvarchar(4))+'-'+cast(@month as nvarchar(2))+'-01')-1, 0)
select @lastmonthlastday = dateadd(day,-(day(cast(@year as nvarchar(4))+'-'+cast(@month as nvarchar(2))+'-01')), cast(@year as nvarchar(4))+'-'+cast(@month as nvarchar(2))+'-01')
select @firstday = cast(convert(datetime, convert(char(4), @year)+right('0'+convert(varchar, @month), 2)+'01') as date)
select @lastday = dateadd(s,-1,dateadd(m, 1, dateadd(mm, datediff(m, 1, cast(@year as nvarchar(4))+'-'+cast(@month as nvarchar(2))+'-01'), 0)))
select CG.Name as [Kapasite Grubu], FK.Name as [Film Çeşidi], S.Code, M.Code as [Makine], M.Capacity as [Kapasite (ay/kg)], CT.Rate as [Makine Film Oranı (%)], case when (M.Capacity * CT.Rate / 100) = 0 then 1 else (M.Capacity * CT.Rate / 100) end as [Makine Aylık Film Kapasitesi (ay/kg)], (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and ProductionDate between @lastmonthfirstday and @lastmonthlastday and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) between @lastmonthfirstday and @lastmonthlastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) as [Geçen Ay Gerçekleşen Üretim (kg)], (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and ProductionDate between @lastmonthfirstday and @lastmonthlastday and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) between @lastmonthfirstday and @lastmonthlastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) / (case when (M.Capacity * CT.Rate / 100) = 0 then 1 else (M.Capacity * CT.Rate / 100) end) * 100 as [Geçen Ay Gerçekleşen Üretim Oranı (%)]
, (case when S.Name = 'Baskı' then ((select isnull(SUM(Quantity), 0) from PrintingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and PrintingWorkOrder in (select Oid from PrintingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Laminasyon' then ((select isnull(SUM(Quantity), 0) from LaminationWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and LaminationWorkOrder in (select Oid from LaminationWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Çekim' then ((select isnull(SUM(Quantity), 0) from FilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and FilmingWorkOrder in (select Oid from FilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Rejenere' then ((select isnull(SUM(Quantity), 0) from RegeneratedWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and RegeneratedWorkOrder in (select Oid from RegeneratedWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Kesim' then ((select isnull(SUM(Quantity), 0) from CuttingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and CuttingWorkOrder in (select Oid from CuttingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Dilme' then ((select isnull(SUM(Quantity), 0) from SlicingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and SlicingWorkOrder in (select Oid from SlicingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Cast Aktarma' then ((select isnull(SUM(Quantity), 0) from CastTransferingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and CastTransferingWorkOrder in (select Oid from CastTransferingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Balonlu Çekim' then ((select isnull(SUM(Quantity), 0) from BalloonFilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and BalloonFilmingWorkOrder in (select Oid from BalloonFilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Cast Dilme' then ((select isnull(SUM(Quantity), 0) from CastSlicingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and CastSlicingWorkOrder in (select Oid from CastSlicingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Cast Rejenere' then ((select isnull(SUM(Quantity), 0) from CastRegeneratedWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and CastRegeneratedWorkOrder in (select Oid from CastRegeneratedWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Cast Çekim' then ((select isnull(SUM(Quantity), 0) from CastFilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and CastFilmingWorkOrder in (select Oid from CastFilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Eco6' then ((select isnull(SUM(Quantity), 0) from Eco6WorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and Eco6WorkOrder in (select Oid from Eco6WorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Eco6 Kesim' then ((select isnull(SUM(Quantity), 0) from Eco6CuttingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and Eco6CuttingWorkOrder in (select Oid from Eco6CuttingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Eco6 Laminasyon' then ((select isnull(SUM(Quantity), 0) from Eco6LaminationWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and Eco6LaminationWorkOrder in (select Oid from Eco6LaminationWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
else 0 end) as [Geçmiş Aylardan Devir Miktar (kg)]
, (case when S.Name = 'Baskı' then ((select isnull(SUM(Quantity), 0) from PrintingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and PrintingWorkOrder in (select Oid from PrintingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Laminasyon' then ((select isnull(SUM(Quantity), 0) from LaminationWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and LaminationWorkOrder in (select Oid from LaminationWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Çekim' then ((select isnull(SUM(Quantity), 0) from FilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and FilmingWorkOrder in (select Oid from FilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Rejenere' then ((select isnull(SUM(Quantity), 0) from RegeneratedWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and RegeneratedWorkOrder in (select Oid from RegeneratedWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Kesim' then ((select isnull(SUM(Quantity), 0) from CuttingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and CuttingWorkOrder in (select Oid from CuttingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Dilme' then ((select isnull(SUM(Quantity), 0) from SlicingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and SlicingWorkOrder in (select Oid from SlicingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Cast Aktarma' then ((select isnull(SUM(Quantity), 0) from CastTransferingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and CastTransferingWorkOrder in (select Oid from CastTransferingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Balonlu Çekim' then ((select isnull(SUM(Quantity), 0) from BalloonFilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and BalloonFilmingWorkOrder in (select Oid from BalloonFilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Cast Dilme' then ((select isnull(SUM(Quantity), 0) from CastSlicingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and CastSlicingWorkOrder in (select Oid from CastSlicingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Cast Rejenere' then ((select isnull(SUM(Quantity), 0) from CastRegeneratedWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and CastRegeneratedWorkOrder in (select Oid from CastRegeneratedWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Cast Çekim' then ((select isnull(SUM(Quantity), 0) from CastFilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and CastFilmingWorkOrder in (select Oid from CastFilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Eco6' then ((select isnull(SUM(Quantity), 0) from Eco6WorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and Eco6WorkOrder in (select Oid from Eco6WorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Eco6 Kesim' then ((select isnull(SUM(Quantity), 0) from Eco6CuttingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and Eco6CuttingWorkOrder in (select Oid from Eco6CuttingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Eco6 Laminasyon' then ((select isnull(SUM(Quantity), 0) from Eco6LaminationWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and Eco6LaminationWorkOrder in (select Oid from Eco6LaminationWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) < @firstday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
else 0 end) / M.Capacity * 100 as [Geçmiş Aylardan Makine Film Oranı (%)]
, (case when S.Name = 'Baskı' then ((select isnull(SUM(Quantity), 0) from PrintingWorkOrder where GCRecord is null and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and PrintingWorkOrder in (select Oid from PrintingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Laminasyon' then ((select isnull(SUM(Quantity), 0) from LaminationWorkOrder where GCRecord is null and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and LaminationWorkOrder in (select Oid from LaminationWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Çekim' then ((select isnull(SUM(Quantity), 0) from FilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and FilmingWorkOrder in (select Oid from FilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Rejenere' then ((select isnull(SUM(Quantity), 0) from RegeneratedWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and RegeneratedWorkOrder in (select Oid from RegeneratedWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Kesim' then ((select isnull(SUM(Quantity), 0) from CuttingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and CuttingWorkOrder in (select Oid from CuttingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Dilme' then ((select isnull(SUM(Quantity), 0) from SlicingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and SlicingWorkOrder in (select Oid from SlicingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Cast Aktarma' then ((select isnull(SUM(Quantity), 0) from CastTransferingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and CastTransferingWorkOrder in (select Oid from CastTransferingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Balonlu Çekim' then ((select isnull(SUM(Quantity), 0) from BalloonFilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and BalloonFilmingWorkOrder in (select Oid from BalloonFilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Cast Dilme' then ((select isnull(SUM(Quantity), 0) from CastSlicingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and CastSlicingWorkOrder in (select Oid from CastSlicingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Cast Rejenere' then ((select isnull(SUM(Quantity), 0) from CastRegeneratedWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and CastRegeneratedWorkOrder in (select Oid from CastRegeneratedWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Cast Çekim' then ((select isnull(SUM(Quantity), 0) from CastFilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and CastFilmingWorkOrder in (select Oid from CastFilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Eco6' then ((select isnull(SUM(Quantity), 0) from Eco6WorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and Eco6WorkOrder in (select Oid from Eco6WorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Eco6 Kesim' then ((select isnull(SUM(Quantity), 0) from Eco6CuttingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and Eco6CuttingWorkOrder in (select Oid from Eco6CuttingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Eco6 Laminasyon' then ((select isnull(SUM(Quantity), 0) from Eco6LaminationWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and Eco6LaminationWorkOrder in (select Oid from Eco6LaminationWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
else 0 end) as [Makine Aylık Doluluğu (kg)] 
, (case when S.Name = 'Baskı' then ((select isnull(SUM(Quantity), 0) from PrintingWorkOrder where GCRecord is null and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and PrintingWorkOrder in (select Oid from PrintingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Laminasyon' then ((select isnull(SUM(Quantity), 0) from LaminationWorkOrder where GCRecord is null and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and LaminationWorkOrder in (select Oid from LaminationWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Çekim' then ((select isnull(SUM(Quantity), 0) from FilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and FilmingWorkOrder in (select Oid from FilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Rejenere' then ((select isnull(SUM(Quantity), 0) from RegeneratedWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and RegeneratedWorkOrder in (select Oid from RegeneratedWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Kesim' then ((select isnull(SUM(Quantity), 0) from CuttingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and CuttingWorkOrder in (select Oid from CuttingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Dilme' then ((select isnull(SUM(Quantity), 0) from SlicingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and SlicingWorkOrder in (select Oid from SlicingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Cast Aktarma' then ((select isnull(SUM(Quantity), 0) from CastTransferingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and CastTransferingWorkOrder in (select Oid from CastTransferingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Balonlu Çekim' then ((select isnull(SUM(Quantity), 0) from BalloonFilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and BalloonFilmingWorkOrder in (select Oid from BalloonFilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Cast Dilme' then ((select isnull(SUM(Quantity), 0) from CastSlicingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and CastSlicingWorkOrder in (select Oid from CastSlicingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Cast Rejenere' then ((select isnull(SUM(Quantity), 0) from CastRegeneratedWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and CastRegeneratedWorkOrder in (select Oid from CastRegeneratedWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Cast Çekim' then ((select isnull(SUM(Quantity), 0) from CastFilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and CastFilmingWorkOrder in (select Oid from CastFilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Eco6' then ((select isnull(SUM(Quantity), 0) from Eco6WorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and Eco6WorkOrder in (select Oid from Eco6WorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Eco6 Kesim' then ((select isnull(SUM(Quantity), 0) from Eco6CuttingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and Eco6CuttingWorkOrder in (select Oid from Eco6CuttingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
when S.Name = 'Eco6 Laminasyon' then ((select isnull(SUM(Quantity), 0) from Eco6LaminationWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) - (select isnull(sum(NetQuantity), 0) from Production where GCRecord is null and Eco6LaminationWorkOrder in (select Oid from Eco6LaminationWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and year(LineDeliveryDate) = @year and month(LineDeliveryDate) = @month and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))))) 
else 0 end) / M.Capacity * 100 as [Makine Aylık Doluluk Oranı (%)]
, (case when S.Name = 'Baskı' then (select isnull(SUM(Quantity), 0) from PrintingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Laminasyon' then (select isnull(SUM(Quantity), 0) from LaminationWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Çekim' then (select isnull(SUM(Quantity), 0) from FilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Rejenere' then (select isnull(SUM(Quantity), 0) from RegeneratedWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Kesim' then (select isnull(SUM(Quantity), 0) from CuttingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Dilme' then (select isnull(SUM(Quantity), 0) from SlicingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Cast Aktarma' then (select isnull(SUM(Quantity), 0) from CastTransferingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Balonlu Çekim' then (select isnull(SUM(Quantity), 0) from BalloonFilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Cast Dilme' then (select isnull(SUM(Quantity), 0) from CastSlicingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Cast Rejenere' then (select isnull(SUM(Quantity), 0) from CastRegeneratedWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Cast Çekim' then (select isnull(SUM(Quantity), 0) from CastFilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Eco6' then (select isnull(SUM(Quantity), 0) from Eco6WorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Eco6 Kesim' then (select isnull(SUM(Quantity), 0) from Eco6CuttingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Eco6 Laminasyon' then (select isnull(SUM(Quantity), 0) from Eco6LaminationWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
else 0 end) as [Gelecek Aylarda Üretilecek Miktar (kg)]
, (case when S.Name = 'Baskı' then (select isnull(SUM(Quantity), 0) from PrintingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Laminasyon' then (select isnull(SUM(Quantity), 0) from LaminationWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Çekim' then (select isnull(SUM(Quantity), 0) from FilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Rejenere' then (select isnull(SUM(Quantity), 0) from RegeneratedWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Kesim' then (select isnull(SUM(Quantity), 0) from CuttingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Dilme' then (select isnull(SUM(Quantity), 0) from SlicingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Cast Aktarma' then (select isnull(SUM(Quantity), 0) from CastTransferingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Balonlu Çekim' then (select isnull(SUM(Quantity), 0) from BalloonFilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Cast Dilme' then (select isnull(SUM(Quantity), 0) from CastSlicingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Cast Rejenere' then (select isnull(SUM(Quantity), 0) from CastRegeneratedWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Cast Çekim' then (select isnull(SUM(Quantity), 0) from CastFilmingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Eco6' then (select isnull(SUM(Quantity), 0) from Eco6WorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Eco6 Kesim' then (select isnull(SUM(Quantity), 0) from Eco6CuttingWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
when S.Name = 'Eco6 Laminasyon' then (select isnull(SUM(Quantity), 0) from Eco6LaminationWorkOrder where GCRecord is null and WorkOrderStatus < 110 and Machine = M.Oid and SalesOrderDetail in (select Oid from SalesOrderDetail where GCRecord is null and cast(LineDeliveryDate as date) > @lastday and Product in (select Oid from Product where GCRecord is null and FilmCode1 in (select Oid from Reciept where FilmKind = CT.FilmKind)))) 
else 0 end) / M.Capacity * 100 as [Gelecek Aylarda Üretilecek Film Oranı (%)] 
from MachineCapacityTarget CT inner join Machine M on M.Oid = CT.Machine inner join CapacityGroup CG on CG.Oid = CT.CapacityGroup inner join FilmKind FK on FK.Oid = CT.FilmKind inner join Station S on S.Oid = M.Station 
where CT.GCRecord is null and CT.[Year] = @year and CT.[Month] = @month ", txtYear.Text, txtMonth.Text);
            orderby = @" order by CG.Name, FK.Name, S.Code, M.Code ";

            if (!string.IsNullOrEmpty(cbCapacityGroup.EditValue.ToString()))
            {
                string list = string.Empty;
                foreach (string item in cbCapacityGroup.EditValue.ToString().Split(','))
                {
                    list += string.Format("'{0}',", item.Trim());
                }
                where += string.Format(" and CG.Oid in ({0})", list.Substring(0, list.Length - 1));
            }
            if (!string.IsNullOrEmpty(cbFilmKind.EditValue.ToString()))
            {
                string list = string.Empty;
                foreach (string item in cbFilmKind.EditValue.ToString().Split(','))
                {
                    list += string.Format("'{0}',", item.Trim());
                }
                where += string.Format(" and FK.Oid in ({0})", list.Substring(0, list.Length - 1));
            }

            SqlDataAdapter adapter = new SqlDataAdapter(select + where + orderby, ((XPObjectSpace)objectSpace).Session.ConnectionString);
            adapter.SelectCommand.CommandTimeout = 0;
            adapter.Fill(dt);
            gridControl1.DataSource = dt;

            if (gridView1.Columns["Kapasite (ay/kg)"] != null)
            {
                gridView1.Columns["Kapasite (ay/kg)"].DisplayFormat.FormatType = FormatType.Numeric;
                gridView1.Columns["Kapasite (ay/kg)"].DisplayFormat.FormatString = "n2";
            }
            if (gridView1.Columns["Makine Film Oranı (%)"] != null)
            {
                gridView1.Columns["Makine Film Oranı (%)"].DisplayFormat.FormatType = FormatType.Numeric;
                gridView1.Columns["Makine Film Oranı (%)"].DisplayFormat.FormatString = "n2";
            }
            if (gridView1.Columns["Makine Aylık Film Kapasitesi (ay/kg)"] != null)
            {
                gridView1.Columns["Makine Aylık Film Kapasitesi (ay/kg)"].DisplayFormat.FormatType = FormatType.Numeric;
                gridView1.Columns["Makine Aylık Film Kapasitesi (ay/kg)"].DisplayFormat.FormatString = "n2";
                if (gridView1.Columns["Makine Aylık Film Kapasitesi (ay/kg)"].Summary.Count == 0)
                    gridView1.Columns["Makine Aylık Film Kapasitesi (ay/kg)"].Summary.Add(DevExpress.Data.SummaryItemType.Sum, "Makine Aylık Film Kapasitesi (ay/kg)", "{0:n2}");
            }
            if (gridView1.Columns["Geçen Ay Gerçekleşen Üretim (kg)"] != null)
            {
                gridView1.Columns["Geçen Ay Gerçekleşen Üretim (kg)"].DisplayFormat.FormatType = FormatType.Numeric;
                gridView1.Columns["Geçen Ay Gerçekleşen Üretim (kg)"].DisplayFormat.FormatString = "n2";
                if (gridView1.Columns["Geçen Ay Gerçekleşen Üretim (kg)"].Summary.Count == 0)
                    gridView1.Columns["Geçen Ay Gerçekleşen Üretim (kg)"].Summary.Add(DevExpress.Data.SummaryItemType.Sum, "Geçen Ay Gerçekleşen Üretim (kg)", "{0:n2}");
            }
            if (gridView1.Columns["Geçen Ay Gerçekleşen Üretim Oranı (%)"] != null)
            {
                gridView1.Columns["Geçen Ay Gerçekleşen Üretim Oranı (%)"].DisplayFormat.FormatType = FormatType.Numeric;
                gridView1.Columns["Geçen Ay Gerçekleşen Üretim Oranı (%)"].DisplayFormat.FormatString = "n2";
            }
            if (gridView1.Columns["Geçmiş Aylardan Devir Miktar (kg)"] != null)
            {
                gridView1.Columns["Geçmiş Aylardan Devir Miktar (kg)"].DisplayFormat.FormatType = FormatType.Numeric;
                gridView1.Columns["Geçmiş Aylardan Devir Miktar (kg)"].DisplayFormat.FormatString = "n2";
                if (gridView1.Columns["Geçmiş Aylardan Devir Miktar (kg)"].Summary.Count == 0)
                    gridView1.Columns["Geçmiş Aylardan Devir Miktar (kg)"].Summary.Add(DevExpress.Data.SummaryItemType.Sum, "Geçmiş Aylardan Devir Miktar (kg)", "{0:n2}");
            }
            if (gridView1.Columns["Geçmiş Aylardan Makine Film Oranı (%)"] != null)
            {
                gridView1.Columns["Geçmiş Aylardan Makine Film Oranı (%)"].DisplayFormat.FormatType = FormatType.Numeric;
                gridView1.Columns["Geçmiş Aylardan Makine Film Oranı (%)"].DisplayFormat.FormatString = "n2";
            }
            if (gridView1.Columns["Makine Aylık Doluluğu (kg)"] != null)
            {
                gridView1.Columns["Makine Aylık Doluluğu (kg)"].DisplayFormat.FormatType = FormatType.Numeric;
                gridView1.Columns["Makine Aylık Doluluğu (kg)"].DisplayFormat.FormatString = "n2";
                if (gridView1.Columns["Makine Aylık Doluluğu (kg)"].Summary.Count == 0)
                    gridView1.Columns["Makine Aylık Doluluğu (kg)"].Summary.Add(DevExpress.Data.SummaryItemType.Sum, "Makine Aylık Doluluğu (kg)", "{0:n2}");
            }
            if (gridView1.Columns["Makine Aylık Doluluk Oranı (%)"] != null)
            {
                gridView1.Columns["Makine Aylık Doluluk Oranı (%)"].DisplayFormat.FormatType = FormatType.Numeric;
                gridView1.Columns["Makine Aylık Doluluk Oranı (%)"].DisplayFormat.FormatString = "n2";
            }
            if (gridView1.Columns["Gelecek Aylarda Üretilecek Miktar (kg)"] != null)
            {
                gridView1.Columns["Gelecek Aylarda Üretilecek Miktar (kg)"].DisplayFormat.FormatType = FormatType.Numeric;
                gridView1.Columns["Gelecek Aylarda Üretilecek Miktar (kg)"].DisplayFormat.FormatString = "n2";
                if (gridView1.Columns["Gelecek Aylarda Üretilecek Miktar (kg)"].Summary.Count == 0)
                    gridView1.Columns["Gelecek Aylarda Üretilecek Miktar (kg)"].Summary.Add(DevExpress.Data.SummaryItemType.Sum, "Gelecek Aylarda Üretilecek Miktar (kg)", "{0:n2}");
            }
            if (gridView1.Columns["Gelecek Aylarda Üretilecek Film Oranı (%)"] != null)
            {
                gridView1.Columns["Gelecek Aylarda Üretilecek Film Oranı (%)"].DisplayFormat.FormatType = FormatType.Numeric;
                gridView1.Columns["Gelecek Aylarda Üretilecek Film Oranı (%)"].DisplayFormat.FormatString = "n2";
            }

            if (xtraTabControl1.SelectedTabPage == xtraTabPage1) xtraTabControl1.SelectedTabPage = xtraTabPage2;
            Cursor.Current = Cursors.Default;
        }
    }
}