select (case when D.SalesOrderStatus = 100 then 'Onay Bekliyor' when D.SalesOrderStatus = 101 then 'Çekim Bekliyor' when D.SalesOrderStatus = 106 then 'Cast Aktarma Bekliyor' when D.SalesOrderStatus = 107 then 'Cast Çekim Bekliyor' when D.SalesOrderStatus = 108 then 'Balonlu Çekim Bekliyor' when D.SalesOrderStatus = 109 then 'Katlama Bekliyor' when D.SalesOrderStatus = 111 then 'Balonlu Kesim Bekliyor' when D.SalesOrderStatus = 112 then 'Dilme Bekliyor' when D.SalesOrderStatus = 113 then 'Laminasyon Bekliyor' when D.SalesOrderStatus = 105 then ' Baský Bekliyor' when D.SalesOrderStatus = 102 then 'Kesim Bekliyor' when D.SalesOrderStatus = 103 then 'Rejenere Bekliyor' when D.SalesOrderStatus = 104 then 'Üretim Bekliyor' when D.SalesOrderStatus = 110 then 'Sevk Bekliyor' when D.SalesOrderStatus = 120 then 'Yükleme Bekliyor' else '' end) as [Durumu], 
	O.OrderNumber as [Sipariþ No], D.LineNumber as [Satýr No], H.Name as [Cari Grup], 
	C.Name as [Müþteri], D.LineInstruction as [Satýr Açýklama], P.Name as [Malzeme Adý], O.OrderDate as [Sipariþ Tarihi], D.LineDeliveryDate as [Satýr Termin], U.Code as [Birimi], D.Quantity as [Miktar], Cu.Code as [Çevrim Birimi], D.cQuantity as [Çevrim Miktarý], 
	(select isnull(sum(GrossQuantity), 0) from Production where GCRecord is null and FilmingWorkOrder is not null and SalesOrderDetail = D.Oid) as [Çekim Üretilen], 
	(select isnull(sum(GrossQuantity), 0) from Production where GCRecord is null and CuttingWorkOrder is not null and SalesOrderDetail = D.Oid) as [Kesim Üretilen], 
	(select isnull(sum(Quantity), 0) from Store where GCRecord is null and SalesOrderDetail = D.Oid and Warehouse = '94291C4A-1626-4FB0-821A-241D8E85D705') as [Sevk Bekleyen], 
	(select isnull(SUM(GrossQuantity), 0) from Production where GCRecord is null and SalesOrderDetail = D.Oid and IsLastProduction = 1) as [Sipariþ Üretilen], 
	(select isnull(sum(GrossQuantity), 0) from Production where Oid in (select Production from Loading where GCRecord is null and SalesOrderDetail = D.Oid)) as [Sevk Edilen] 
from SalesOrderDetail D inner join SalesOrder O on O.Oid = D.SalesOrder inner join Contact C on C.Oid = O.Contact left outer join ContactGroup G on G.Oid = C.ContactGroup left outer join HCategory H on H.Oid = G.Oid and H.GCRecord is null inner join Product P on P.Oid = D.Product left outer join Unit U on U.Oid = D.Unit left outer join Unit Cu on Cu.Oid = D.cUnit 
where D.GCRecord is null and D.SalesOrderStatus < 200 
order by O.OrderDate
