--Termine Göre
select ROW_NUMBER() over (partition by M.Code order by M.Code, D.LineDeliveryDate asc) AS OptimizedSequenceNumber, W.SequenceNumber, W.WorkOrderNumber, W.WorkOrderDate, M.Code, C.Name, P.Name, O.OrderNumber, D.LineNumber, D.LineDeliveryDate, D.cQuantity, W.Quantity, (case when W.PrintForm = 0 then 'Ters' else 'Düz' end) as PrintForm, W.ColorCount, W.CylinderRepetition from PrintingWorkOrder W inner join SalesOrderDetail D on D.Oid = W.SalesOrderDetail inner join SalesOrder O on O.Oid = D.SalesOrder inner join Contact C on C.Oid = O.Contact inner join Product P on P.Oid = D.Product inner join Machine M on M.Oid = W.Machine where W.GCRecord is null and W.WorkOrderStatus < 110 order by M.Code, D.LineDeliveryDate 

--Termine Göre Planlama Öncelikli
select ROW_NUMBER() over (partition by Machine order by Machine, SalesOrderType, LineDeliveryDate asc) AS OptimizedSequenceNumber, * from (select 'Satýþ Sipariþi' as SalesOrderType, W.SequenceNumber, W.WorkOrderNumber, W.WorkOrderDate, M.Code as Machine, C.Name as Contact, P.Name as Product, O.OrderNumber, D.LineNumber, D.LineDeliveryDate, D.cQuantity, W.Quantity, (case when W.PrintForm = 0 then 'Ters' else 'Düz' end) as PrintForm, W.ColorCount, W.CylinderRepetition from PrintingWorkOrder W inner join SalesOrderDetail D on D.Oid = W.SalesOrderDetail inner join SalesOrder O on O.Oid = D.SalesOrder inner join Contact C on C.Oid = O.Contact inner join Product P on P.Oid = D.Product inner join Machine M on M.Oid = W.Machine where W.GCRecord is null and W.WorkOrderStatus < 110 and O.SalesOrderType in (0, 2, 3, 4)
UNION 
select 'Planlama Sipariþi' as SalesOrderType, W.SequenceNumber, W.WorkOrderNumber, W.WorkOrderDate, M.Code, C.Name, P.Name, O.OrderNumber, D.LineNumber, D.LineDeliveryDate, D.cQuantity, W.Quantity, (case when W.PrintForm = 0 then 'Ters' else 'Düz' end) as PrintForm, W.ColorCount, W.CylinderRepetition from PrintingWorkOrder W inner join SalesOrderDetail D on D.Oid = W.SalesOrderDetail inner join SalesOrder O on O.Oid = D.SalesOrder inner join Contact C on C.Oid = O.Contact inner join Product P on P.Oid = D.Product inner join Machine M on M.Oid = W.Machine where W.GCRecord is null and W.WorkOrderStatus < 110 and O.SalesOrderType in (1, 5, 6, 7)) T order by Machine, SalesOrderType, LineDeliveryDate

--Termine Göre Müþteri Öncelikli
select ROW_NUMBER() over (partition by Machine order by Machine, SalesOrderType desc, LineDeliveryDate asc) AS OptimizedSequenceNumber, * from (select 'Satýþ Sipariþi' as SalesOrderType, W.SequenceNumber, W.WorkOrderNumber, W.WorkOrderDate, M.Code as Machine, C.Name as Contact, P.Name as Product, O.OrderNumber, D.LineNumber, D.LineDeliveryDate, D.cQuantity, W.Quantity, (case when W.PrintForm = 0 then 'Ters' else 'Düz' end) as PrintForm, W.ColorCount, W.CylinderRepetition from PrintingWorkOrder W inner join SalesOrderDetail D on D.Oid = W.SalesOrderDetail inner join SalesOrder O on O.Oid = D.SalesOrder inner join Contact C on C.Oid = O.Contact inner join Product P on P.Oid = D.Product inner join Machine M on M.Oid = W.Machine where W.GCRecord is null and W.WorkOrderStatus < 110 and O.SalesOrderType in (0, 2, 3, 4)
UNION 
select 'Planlama Sipariþi' as SalesOrderType, W.SequenceNumber, W.WorkOrderNumber, W.WorkOrderDate, M.Code, C.Name, P.Name, O.OrderNumber, D.LineNumber, D.LineDeliveryDate, D.cQuantity, W.Quantity, (case when W.PrintForm = 0 then 'Ters' else 'Düz' end) as PrintForm, W.ColorCount, W.CylinderRepetition from PrintingWorkOrder W inner join SalesOrderDetail D on D.Oid = W.SalesOrderDetail inner join SalesOrder O on O.Oid = D.SalesOrder inner join Contact C on C.Oid = O.Contact inner join Product P on P.Oid = D.Product inner join Machine M on M.Oid = W.Machine where W.GCRecord is null and W.WorkOrderStatus < 110 and O.SalesOrderType in (1, 5, 6, 7)) T order by Machine, SalesOrderType desc, LineDeliveryDate