select C.Name as [Müþteri], PG.Name as [Ürün Grubu], PT.Name as [Ürün Tipi], PK.Name as [Ürün Cinsi], P.Code as [Stok Kodu]
, P.Name as [Stok Adý]
, P.Width as [S.En]
, P.Height as [S.Boy]
, P.Thickness as [S.Kalýnlýk]
, P.Lenght as [S.Uzunluk]
, P.Density as [S.Yoðunluk]
, A.Name as [S.Katký]
, P.AdditiveRate as [S.Katký Oraný]
, (case when P.BellowsStatus = 0 then 'Yok' when P.BellowsStatus = 1 then 'Yan Körük' when P.BellowsStatus = 2 then 'Alt Körük' else 'Üst Körük' end) as [S.Körük Durumu]
, P.Bellows as [S.Körük]
, (case when P.CapStatus = 0 then 'Kapaksýz' else 'Kapaklý' end) as [S.Kapak Durumu]
, P.Cap as [S.Kapak]
, (case when P.PerforationStatus = 0 then 'Perforesiz' else 'Perforeli' end) as [S.Perfore]
, (case when P.BandStatus = 0 then 'Bantsýz' else 'Bantlý' end) as [S.Band Durumu]
, (case when P.HangingLocation = 0 then 'Var' else 'Yok' end) as [S.Asma Yeri]
, (case when P.Corona = 0 then 'Yok' when P.Corona = 1 then 'Tek Taraf Full' when P.Corona = 2 then 'Çift Taraf Full' when P.Corona = 3 then 'Tek Taraf Parsiyel' else 'Çift Taraf Parsiyel' end) as [S.Korona]
, (case when P.CoronaDirection = 0 then 'Ýç' when P.CoronaDirection = 1 then 'Dýþ' else 'Ýç-Dýþ' end) as [S.Korona Yönü]
, P.CoronaPartial as [S.Korona Parsiyel]
, (case when P.AdhesionType = 0 then 'Yok' when P.AdhesionType = 1 then 'AA' when P.AdhesionType = 2 then 'AB' else 'BB' end) as [S.Boy]
, (case when P.HandleWeld = 0 then 'Yok' when P.HandleWeld = 1 then 'Oval' when P.HandleWeld = 2 then 'Çavuþ' when P.HandleWeld = 3 then 'Böbrek' else 'Çift Çene' end) as [S.Boy]
, (case when P.HandleType = 0 then 'Yok' when P.HandleType = 1 then 'El Geçme' when P.HandleType = 2 then 'Yumuþak' when P.HandleType = 3 then 'Crosshandle' else 'Takviye' end) as [S.Boy]
, (case when P.HandsOnType = 0 then 'Yok' when P.HandsOnType = 1 then 'Oval' else 'Böbrek' end) as [S.Boy]
, (case when P.Laminated = 0 then 'Yok' else 'Var' end) as [S.Lamine]
, P.FilmCode1 as [S.Film Kodu 1]
, P.FilmCode1Thickness as [S.Film Kodu 1 Kalýnlýk]
, P.FilmCode2 as [S.Film kodu 2]
, P.FilmCode2Thickness as [S.Film Kodu 2 Kalýnlýk]
, P.ShippingFilmType as [S.Sevk Film Þekli]
, (case when P.PunchStatus = 0 then 'Deliksiz' else 'Delikli' end) as [S.Delik Durumu]
, P.PunchType as [S.Delik Türü]
, P.Block as [S.Blok]
, (case when P.Embossing = 0 then 'Yok' else 'Var' end) as [S.Gofraj]
, MC.Name as [S.Mlz.Rengi]
, P.BladeDeep as [S.Býçak Derinliði]
, P.PieceWeight as [S.Adet Að.]
, PPT.Name as [S.Üretim Amb.Þekli]
, SPT.Name as [S.Sevk Amb.Þekli]
, BT.Name as [S.Boy]
, P.RollWeight as [S.Rl.Að.]
, P.RollDiameter as [S.Rl.Çapý]
, P.NetKg as [S.Net Kg]
, P.OuterPackingRollCount as [S.Dýþ Amb.Rl.Say.]
, P.InnerPackingInPiece as [S.Ýç Amb.Ad.Say.]
, P.OuterPackingInPiece as [S.Dýþ Amb.Ýç Ad.Say.]
, P.PackageWeight as [S.Pk.Að.]
, IP.Name as [S.Ýç Amb.]
, P.InnerPackingBarcode as [S.Ýç Amb.Barkod]
, OP.Name as [S.Dýþ Amb.]
, P.OuterPackingBarcode as [S.Dýþ Amb.Barkod]
, P.PalettePackageCount as [S.Palet Adet Say.]
, PN.Name as [S.Baský Adý]
, P.PrintingColors as [S.Baský Renkleri]
, (case when P.PrintForm = 0 then 'Ters' else 'Düz' end) as [S.Baský Þekli]
, P.RollDirection as [S.Rulo Yönü]
, P.ExpirationDate as [S.Son Kull.Tarihi]
, PR.Name as [S.Boy]
, (case when P.PrintDirection = 0 then 'Ön' when P.PrintDirection = 1 then 'Ön/Arka' when P.PrintDirection = 2 then 'Ýç' when P.PrintDirection = 3 then 'Dýþ' when P.PrintDirection = 4 then 'Çift Taraf' else 'Tek Taraf' end) as [S.Baský Yönü]
, P.Barcode as [S.Barkod]
, P.BussinesRegistrationNumber as [S.Ýþletme Kayýt No]
, (case when P.Logo = 0 then 'Yok' else 'Var' end) as [S.Logo]
, (case when P.TKBPermission = 0 then 'Yok' else 'Var' end) as [S.TKB]

, (select top 1 Width from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.En]
, (select top 1 Height from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Boy]
, (select top 1 Thickness from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Kalýnlýk]
, (select top 1 Gsm from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Gsm]
, (select top 1 Lenght from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Uzunluk]
, (select top 1 (case when BellowsStatus = 0 then 'Yok' when BellowsStatus = 1 then 'Yan Körük' when BellowsStatus = 2 then 'Alt Körük' else 'Üst Körük' end) from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Körük Durumu]
, (select top 1 Bellows from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Körük]
, (select top 1 (case when CapStatus = 0 then 'Kapaksýz' else 'Kapaklý' end) from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Kapak Durumu]
, (select top 1 Cap from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Kapak]
, (select top 1 (case when Corona = 0 then 'Yok' when Corona = 1 then 'Tek Taraf Full' when Corona = 2 then 'Çift Taraf Full' when Corona = 3 then 'Tek Taraf Parsiyel' else 'Çift Taraf Parsiyel' end) from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Korona]
, (select top 1 (case when CoronaDirection = 0 then 'Ýç' when CoronaDirection = 1 then 'Dýþ' else 'Ýç-Dýþ' end) from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Korona Yönü]
, (select top 1 CoronaPartial from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Korona Parsiyel]
, (select top 1 (select Name from PrintName where Oid = PrintName) from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Baský Adý]
, (select top 1 Density from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Yoðunluk]
, (select top 1 (select Name from Additive where Oid = Additive) from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Karýþým]
, (select top 1 AdditiveRate from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Karýþým Oraný]
, (select top 1 RollWeight from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Rulo Að.]
, (select top 1 RollDiameter from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Rulo Çapý]
, (select top 1 RollCount from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Rulo Sayýsý]
, (select top 1 MinimumRollWeight from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Min.Rl.Að.]
, (select top 1 MaximumRollWeight from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Max.Rl.Að.]
, (select top 1 WayCount from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Yol Sayýsý]
, (select top 1 GramM2 from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.GramM2]
, (select top 1 GramMetretul from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Gr.Metretül]
, (select top 1 InflationRate from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Þiþirme Oraný]
, (select top 1 (select Name from ShippingPackageType where Oid = ShippingPackageType) from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Sevk Amb.Þekli]
, (select top 1 (select Name from ShippingFilmType where Oid = ShippingFilmType) from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Sek Film Þekli]
, (select top 1 (select Name from MaterialColor where Oid = MaterialColor) from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Mlz.Rengi]
, (select top 1 (case when Embossing = 0 then 'Yok' else 'Var' end) from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Gofraj]
, (select top 1 (select Name from Bobbin where Oid = Bobbin) from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Masura]
, (select top 1 (select Name from Palette where Oid = Palette) from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Palet]
, (select top 1 PaletteLayout from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Plt.Diz.]
, (select top 1 PaletteBobbinCount from FilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Ç.Pl.Bobin Say.]

, (select top 1 Width from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.En]
, (select top 1 Thickness from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Kalýnlýk]
, (select top 1 Lenght from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Uzunluk]
, (select top 1 Density from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Yoðunluk]
, (select top 1 Size from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Ebat]
, (select top 1 (select Name from Bobbin where Oid = Bobbin) from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Masura]
, (select top 1 RollWeight from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Rl.Að.]
, (select top 1 MinimumRollWeight from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Min.Rl.Að.]
, (select top 1 MaximumRollWeight from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Max.Rl.Að.]
, (select top 1 RollDiameter from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Rl.Çapý]
, (select top 1 RollCount from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Rl.Say.]
, (select top 1 BandCount from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Band Say.]
, (select top 1 (select Name from MaterialColor where Oid = MaterialColor) from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Mlz.Rengi]
, (select top 1 (select Name from PrintName where Oid = PrintName) from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Baský Adý]
, (select top 1 Anilox from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Anilox]
, (select top 1 Plate from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Kliþe]
, (select top 1 ColorCount from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Renk Say.]
, (select top 1 LineSpeed from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Hat Hýzý]
, (select top 1 PrintingColors from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Baský Renkleri]
, (select top 1 (case when PrintForm = 0 then 'Ters' else 'Düz' end) from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Baský Þekli]
, (select top 1 (case when PrintDirection = 0 then 'Ön' when PrintDirection = 1 then 'Ön/Arka' when PrintDirection = 2 then 'Ýç' when PrintDirection = 3 then 'Dýþ' when PrintDirection = 4 then 'Çift Taraf' else 'Tek Taraf' end) from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Baský Yönü]
, (select top 1 (case when PrintWorkStatus = 0 then 'Tekrar' when PrintWorkStatus = 1 then 'Yeni' when PrintWorkStatus = 2 then 'Revizyon' when PrintWorkStatus = 3 then 'Tasarým' when PrintWorkStatus = 4 then 'Ýlk' else 'Ýade' end) from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Ýþ Durumu]
, (select top 1 RollDirection from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Rl.Yönü]
, (select top 1 ClicheBand from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Kliþe Bandý]
, (select top 1 ClicheThickness from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Kliþe Kal.]
, (select top 1 ClicheCode from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Kliþe Kodu]
, (select top 1 (case when Logo = 0 then 'Yok' else 'Var' end) from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Logo]
, (select top 1 Barcode from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Barkod]
, (select top 1 (select Name from ShippingPackageType where Oid = ShippingPackageType) from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Sevk Amb.Þekli]
, (select top 1 (select Name from OuterPacking where Oid = OuterPacking) from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Dýþ Amb.]
, (select top 1 (select Name from Palette where Oid = Palette) from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Palet]
, (select top 1 PaletteBobbinCount from PrintingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [B.Plt.Diz.]

, (select top 1 Width from SlicingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [D.En]
, (select top 1 Height from SlicingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [D.Boy]
, (select top 1 Thickness from SlicingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [D.Kalýnlýk]
, (select top 1 Lenght from SlicingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [D.Uzunluk]
, (select top 1 Density from SlicingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [D.Yoðunluk]
, (select top 1 (select Name from Bobbin where Oid = Bobbin) from SlicingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [D.Masura]
, (select top 1 RollWeight from SlicingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [D.Rl.Að.]
, (select top 1 MinimumRollWeight from SlicingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [D.Min.Rl.Að.]
, (select top 1 MaximumRollWeight from SlicingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [D.Max.Rl.Að.]
, (select top 1 GramMetretul from SlicingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [D.Gram Metretül]
, (select top 1 SlicingWidth from SlicingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [D.Dilme Eni]
, (select top 1 RollDiameter from SlicingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [D.Rl.Çapý]
, (select top 1 RollCount from SlicingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [D.Rl.Say.]
, (select top 1 (select Name from MaterialColor where Oid = MaterialColor) from SlicingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [D.Mlz.Rengi]
, (select top 1 (select Name from PrintName where Oid = PrintName) from SlicingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [D.Baský Adý]
, (select top 1 (case when PrintDirection = 0 then 'Ön' when PrintDirection = 1 then 'Ön/Arka' when PrintDirection = 2 then 'Ýç' when PrintDirection = 3 then 'Dýþ' when PrintDirection = 4 then 'Çift Taraf' else 'Tek Taraf' end) from SlicingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [D.Baský Yönü]
, (select top 1 (case when PrintWorkStatus = 0 then 'Tekrar' when PrintWorkStatus = 1 then 'Yeni' when PrintWorkStatus = 2 then 'Revizyon' when PrintWorkStatus = 3 then 'Tasarým' when PrintWorkStatus = 4 then 'Ýlk' else 'Ýade' end) from SlicingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [D.Ýþ Durumu]
, (select top 1 (select Name from ShippingPackageType where Oid = ShippingPackageType) from SlicingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [D.Sevk Amb.Þekli]
, (select top 1 (select Name from OuterPacking where Oid = OuterPacking) from SlicingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [D.Dýþ Amb.]
, (select top 1 (select Name from Palette where Oid = Palette) from SlicingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [D.Palet]
, (select top 1 PaletteLayout from SlicingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [D.Plt.Diz.]
, (select top 1 PaletteBobbinCount from SlicingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [D.Plt.Bobin Say.]

, (select top 1 Width from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.En]
, (select top 1 Height from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Boy]
, (select top 1 Thickness from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Kalýnlýk]
, (select top 1 (case when BellowsStatus = 0 then 'Yok' when BellowsStatus = 1 then 'Yan Körük' when BellowsStatus = 2 then 'Alt Körük' else 'Üst Körük' end) from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Körük Durumu]
, (select top 1 Bellows from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Körük]
, (select top 1 (case when CapStatus = 0 then 'Kapaksýz' else 'Kapaklý' end) from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Kapak Durumu]
, (select top 1 Cap from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Kapak]
, (select top 1 (case when PerforationStatus = 0 then 'Perforesiz' else 'Perforeli' end) from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Perfore]
, (select top 1 (case when BandStatus = 0 then 'Bantsýz' else 'Bantlý' end) from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Bant Durumu]
, (select top 1 (case when HangingLocation = 0 then 'Var' else 'Yok' end) from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Asma Yeri]
, (select top 1 (case when HandleWeld = 0 then 'Yok' when HandleWeld = 1 then 'Oval' when HandleWeld = 2 then 'Çavuþ' when HandleWeld = 3 then 'Böbrek' else 'Çift Çene' end) from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.El Geçme]
, (select top 1 Block from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Blok]
, (select top 1 (select Name from PrintName where Oid = PrintName) from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Baský Adý]
, (select top 1 BladeWidth from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Býçak Eni]
, (select top 1 BladeDeep from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Býçak Derinliði]
, (select top 1 Density from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Yoðunluk]
, (select top 1 PackageWeight from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Paket Að.]
, (select top 1 PieceWeight from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Adet Að.]
, (select top 1 MinimumPieceWeight from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Min.Pk.Að.]
, (select top 1 MaximumPieceWeight from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Max.Pk.Að.]
, (select top 1 PackageCount from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Paket Say.]
, (select top 1 (select Name from ShippingFilmType where Oid = ShippingFilmType) from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Sevk Film Þekli]
, (select top 1 WayCount from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Yol Sayýsý]
, (select top 1 (select Name from ShippingPackageType where Oid = ShippingPackageType) from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Sevk Amb.Þekli]
, (select top 1 GramM2 from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.GramM2]
, (select top 1 GramMetretul from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Gram Metretül]
, (select top 1 (case when Embossing = 0 then 'Yok' else 'Var' end) from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Gofraj]
, (select top 1 (select Name from OuterPacking where Oid = OuterPacking) from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Dýþ Amb.]
, (select top 1 (select Name from InnerPacking where Oid = InnerPacking) from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Ýç Amb.]
, (select top 1 Bobbin from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Masura]
, (select top 1 (select Name from Palette where Oid = Palette) from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Palet]
, (select top 1 PaletteLayout from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Plt Diz.]
, (select top 1 PaletteBobbinCount from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Plt.Bobin Say.]
, (select top 1 DeckCount from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Koli Say.]
, (select top 1 SupportBandColor from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Takviye Bandý Renk]
, (select top 1 SupportBandThickness from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Takviye Bandý Kalýnlýk]
, (select top 1 SupportBandSize from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Takviye Bandý Ebat]
, (select top 1 SupportBandNote from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Takviye Bandý Açýklama]
, (select top 1 OuterPackingPackageCount from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Dýþ Amb.Pk.Say.]
, (select top 1 InnerPackingPieceCount from CuttingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [K.Ýç Amb.Ad.Say.]

, (select top 1 Width from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.En]
, (select top 1 Height from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Boy]
, (select top 1 Thickness from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Kalýnlýk]
, (select top 1 Lenght from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Uzunluk]
, (select top 1 Density from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Yoðunluk]
, (select top 1 RollDiameter from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Rl.Çapý]
, (select top 1 RollWeight from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Rl.Að.]
, (select top 1 MinimumRollWeight from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Min.Rl.Að.]
, (select top 1 MaximumRollWeight from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Max.Rl.Að]
, (select top 1 (select Name from Bobbin where Oid = Bobbin) from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Masura]
, (select top 1 SubFilm from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Alt Film]
, (select top 1 SubFilmThickness from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Alt Film Kalýnlýk]
, (select top 1 SubFilmWidth from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Alt Film En]
, (select top 1 SubFilmLength from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Alt Film Uz.]
, (select top 1 SubFilmTension from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Alt Film Tansiyon]
, (select top 1 TopFilm from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Üst Film]
, (select top 1 TopFilmThickness from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Üst Film Kalýnlýk]
, (select top 1 TopFilmWidth from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Üst Film En]
, (select top 1 TopFilmLength from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Üst Film Uz.]
, (select top 1 TopFilmTension from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Üst Film Tansiyon]
, (select top 1 CoatingRollerSize from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Kaplama Merdane Ebatý]
, (select top 1 SingleComponent from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Tek Komp.]
, (select top 1 SingleComponentReservoir from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Tek Komp.Hazne]
, (select top 1 SingleComponentHose from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Tek Komp.Hortum]
, (select top 1 SingleComponentSprayGun from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Tek Komp.Tabanca]
, (select top 1 DoubleComponent from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Çift Komp.]
, (select top 1 DoubleComponentA from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Çift Komp.A]
, (select top 1 DoubleComponentAReservoir from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Çift Komp.A Hazne]
, (select top 1 DoubleComponentAHose from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Çift Komp.A Hortum]
, (select top 1 DoubleComponentASprayGun from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Çift Komp.A Tabanca]
, (select top 1 DoubleComponentB from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Çift Komp.B]
, (select top 1 DoubleComponentBReservoir from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Çift Komp.B Hazne]
, (select top 1 DoubleComponentBHose from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Çift Komp.B Hortum]
, (select top 1 DoubleComponentBSprayGun from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Çift Komp.B Tabanca]
, (select top 1 Performance from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Verim]
, (select top 1 LineSpeed from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Hat Hýzý]
, (select top 1 Tension from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Tansiyon]
, (select top 1 ShippingPackageType from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Sevk Amb.Þekli]
, (select top 1 (select Name from Palette where Oid = Palette) from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Palet]
, (select top 1 PaletteBobbinCount from LaminationWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [L.Plt.Bobin Say.]

, (select top 1 Width from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.En]
, (select top 1 Height from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Boy]
, (select top 1 Thickness from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Kalýnlýk]
, (select top 1 Lenght from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Uzunluk]
, (select top 1 (case when BellowsStatus = 0 then 'Yok' when BellowsStatus = 1 then 'Yan Körük' when BellowsStatus = 2 then 'Alt Körük' else 'Üst Körük' end) from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Körük Durumu]
, (select top 1 Bellows from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Körük]
, (select top 1 (case when CapStatus = 0 then 'Kapaksýz' else 'Kapaklý' end) from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Kapak Durumu]
, (select top 1 Cap from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Kapak]
, (select top 1 (case when Corona = 0 then 'Yok' when Corona = 1 then 'Tek Taraf Full' when Corona = 2 then 'Çift Taraf Full' when Corona = 3 then 'Tek Taraf Parsiyel' else 'Çift Taraf Parsiyel' end) from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Korona]
, (select top 1 (case when CoronaDirection = 0 then 'Ýç' when CoronaDirection = 1 then 'Dýþ' else 'Ýç-Dýþ' end) from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Korona Yönü]
, (select top 1 CoronaPartial from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Korona Parsiyel]
, (select top 1 (select Name from PrintName where Oid = PrintName) from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Baský Adý]
, (select top 1 Density from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Yoðunluk]
, (select top 1 (select Name from Additive where Oid = Additive) from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Katký]
, (select top 1 AdditiveRate from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Katký Oraný]
, (select top 1 RollWeight from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Rl.Að.]
, (select top 1 RollDiameter from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Rl.Çapý]
, (select top 1 RollCount from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Rl.Say.]
, (select top 1 MinimumRollWeight from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Min.Rl.Að.]
, (select top 1 MaximumRollWeight from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Max.Rl.Að.]
, (select top 1 WayCount from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Yol Say.]
, (select top 1 GramM2 from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.GramM2]
, (select top 1 GramMetretul from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Gram Metretül]
, (select top 1 InflationRate from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Þiþirme Oraný]
, (select top 1 (select Name from ShippingPackageType where Oid = ShippingPackageType) from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Sevk Amb.Þekli]
, (select top 1 (select Name from ShippingFilmType where Oid = ShippingFilmType) from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Sevk Film Þekli]
, (select top 1 (select Name from MaterialColor where Oid = MaterialColor) from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Mlz.Rengi]
, (select top 1 (case when Embossing = 0 then 'Yok' else 'Var' end) from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Gofraj]
, (select top 1 (select Name from OuterPacking where Oid = OuterPacking) from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Dýþ Amb.]
, (select top 1 (select Name from Bobbin where Oid = Bobbin) from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Masura]
, (select top 1 (select Name from Palette where Oid = Palette) from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Palet]
, (select top 1 PaletteLayout from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Plt.Diz.]
, (select top 1 PaletteBobbinCount from BalloonFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [CPP.Plt.Bobin Say.]

, (select top 1 Width from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.En]
, (select top 1 Height from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Boy]
, (select top 1 Thickness from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Kalýnlýk]
, (select top 1 Lenght from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Uzunluk]
, (select top 1 (case when BellowsStatus = 0 then 'Yok' when BellowsStatus = 1 then 'Yan Körük' when BellowsStatus = 2 then 'Alt Körük' else 'Üst Körük' end) from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Körük Durumu]
, (select top 1 Bellows from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Körük]
, (select top 1 (case when CapStatus = 0 then 'Kapaksýz' else 'Kapaklý' end) from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Kapak Durumu]
, (select top 1 Cap from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Kapak]
, (select top 1 (case when Corona = 0 then 'Yok' when Corona = 1 then 'Tek Taraf Full' when Corona = 2 then 'Çift Taraf Full' when Corona = 3 then 'Tek Taraf Parsiyel' else 'Çift Taraf Parsiyel' end) from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Korona]
, (select top 1 (case when CoronaDirection = 0 then 'Ýç' when CoronaDirection = 1 then 'Dýþ' else 'Ýç-Dýþ' end) from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Korona Yönü]
, (select top 1 CoronaPartial from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Korona Parsiyel]
, (select top 1 (select Name from PrintName where Oid = PrintName) from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Baský Adý]
, (select top 1 Density from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Yoðunluk]
, (select top 1 (select Name from Additive where Oid = Additive) from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Katký]
, (select top 1 AdditiveRate from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Katký Oraný]
, (select top 1 RollWeight from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Rl.Að.]
, (select top 1 RollDiameter from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Rl.Çapý]
, (select top 1 RollCount from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Rl.Say.]
, (select top 1 MinimumRollWeight from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Min.Rl.Að.]
, (select top 1 MaximumRollWeight from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Max.Rl.Að.]
, (select top 1 WayCount from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Yol Say.]
, (select top 1 GramM2 from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.GramM2]
, (select top 1 GramMetretul from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Gram Metretül]
, (select top 1 InflationRate from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Þiþirme Oraný]
, (select top 1 (select Name from ShippingPackageType where Oid = ShippingPackageType) from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Sevk Amb.Þekli]
, (select top 1 (select Name from ShippingFilmType where Oid = ShippingFilmType) from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Sevk Film Þekli]
, (select top 1 (select Name from MaterialColor where Oid = MaterialColor) from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Mlz.Rengi]
, (select top 1 (case when Embossing = 0 then 'Yok' else 'Var' end) from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Gofraj]
, (select top 1 (select Name from OuterPacking where Oid = OuterPacking) from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Dýþ Amb.]
, (select top 1 (select Name from Bobbin where Oid = Bobbin) from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Masura]
, (select top 1 (select Name from Palette where Oid = Palette) from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Palet]
, (select top 1 PaletteLayout from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Plt.Diz.]
, (select top 1 PaletteBobbinCount from CastFilmingWorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Cast.Plt.Bobin Say.]

, (select top 1 Width from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.En]
, (select top 1 Thickness from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.Kalýnlýk]
, (select top 1 Lenght from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.Uzunluk]
, (select top 1 (select Name from Additive where Oid = Additive) from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.Katký]
, (select top 1 AdditiveRate from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.Katký Oraný]
, (select top 1 GramM2 from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.GramM2]
, (select top 1 GramMetretul from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.Gram Metretül]
, (select top 1 M2 from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.M2]
, (select top 1 RollWeight from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.Rl.Að.]
, (select top 1 MinimumRollWeight from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.Min.Rl.Að.]
, (select top 1 MaximumRollWeight from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.Max.Rl.Að.]
, (select top 1 (select Name from MaterialColor where Oid = MaterialColor) from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.Mlz.Rengi]
, (select top 1 LotNumber from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.Lot No]
, (select top 1 S1Rate from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.S1 Katý]
, (select top 1 MRate from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.M Katý]
, (select top 1 S2Rate from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.S2 Katý]
, (select top 1 RollDiameter from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.Rl.Çapý]
, (select top 1 (select Name from Bobbin where Oid = Bobbin) from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.Masura]
, (select top 1 (select Name from ShippingPackageType where Oid = ShippingPackageType) from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.Sevk Amb.Þekli]
, (select top 1 (select Name from ShippingFilmType where Oid = ShippingFilmType) from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.Sevk Film Þekli]
, (select top 1 (select Name from OuterPacking where Oid = OuterPacking) from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.Dýþ Amb.]
, (select top 1 (select Name from Palette where Oid = Palette) from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.Palet]
, (select top 1 PaletteLayout from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.Plt.Diz.]
, (select top 1 PaletteBobbinCount from Eco6WorkOrder where GCRecord is null and SalesOrderDetail = D.Oid) as [Eco6.Plt.Bobin Say.]

from SalesOrderDetail D inner join Product P on P.Oid = D.Product left outer join ProductGroup PG on PG.Oid = P.ProductGroup left outer join ProductType PT on PT.Oid = P.ProductType left outer join ProductKind PK on PK.Oid = P.productKind inner join SalesOrder O on O.Oid = D.SalesOrder inner join Contact C on C.Oid = O.Contact left outer join Additive A on A.Oid = P.Additive left outer join MaterialColor MC on MC.Oid = P.MaterialColor left outer join ProductionPackageType PPT on PPT.Oid = P.ProductionPackageType left outer join ShippingPackageType SPT on SPT.Oid = P.ShippingPackageType left outer join BobbinType BT on BT.Oid = P.BobbinType left outer join InnerPacking IP on IP.Oid = P.InnerPacking left outer join OuterPacking OP on OP.Oid = P.OuterPacking left outer join PrintName PN on PN.Oid = P.PrintName left outer join PrintRate PR on PR.Oid = P.PrintRate 
where D.GCRecord is null 