USE SanatERP
GO
DECLARE @LOGNAME VARCHAR(100)
SET @LOGNAME = (SELECT name FROM sys.database_files WHERE type_desc = 'LOG')
ALTER DATABASE SanatERP SET RECOVERY SIMPLE WITH NO_WAIT
DBCC SHRINKFILE(@LOGNAME)
ALTER DATABASE SanatERP SET RECOVERY FULL WITH NO_WAIT
GO
