declare @begindate datetime, @enddate datetime
set @begindate = '2017-04-26 08:15'	set @enddate = '2017-04-27 08:25'
select [Ýstasyon], [Sonraki Ýstasyon], SUM([Brüt]) as [Brüt], SUM([Net]) as [Net] from (select S.Code as [Ýstasyon], (case when P.FilmingWorkOrder is not null then (select Name from Station where Oid = (select NextStation from FilmingWorkOrder where Oid = P.FilmingWorkOrder)) else '' end) as [Sonraki Ýstasyon], P.GrossQuantity as [Brüt], P.NetQuantity as [Net] from Production P inner join Machine M on M.Oid = P.Machine inner join Station S on S.Oid = M.Station where P.GCRecord is null and FilmingWorkOrder is not null and P.ProductionDate between @begindate and @enddate) T group by [Ýstasyon], [Sonraki Ýstasyon] 
UNION 
select [Ýstasyon], [Sonraki Ýstasyon], SUM([Brüt]) as [Brüt], SUM([Net]) as [Net] from (select S.Code as [Ýstasyon], (case when P.CastFilmingWorkOrder is not null then (select Name from Station where Oid = (select NextStation from CastFilmingWorkOrder where Oid = P.CastFilmingWorkOrder)) else '' end) as [Sonraki Ýstasyon], P.GrossQuantity as [Brüt], P.NetQuantity as [Net] from Production P inner join Machine M on M.Oid = P.Machine inner join Station S on S.Oid = M.Station where P.GCRecord is null and CastFilmingWorkOrder is not null and P.ProductionDate between @begindate and @enddate) T group by [Ýstasyon], [Sonraki Ýstasyon] 
UNION 
select [Ýstasyon], [Sonraki Ýstasyon], SUM([Brüt]) as [Brüt], SUM([Net]) as [Net] from (select S.Code as [Ýstasyon], (case when P.CastTransferingWorkOrder is not null then (select Name from Station where Oid = (select NextStation from CastTransferingWorkOrder where Oid = P.CastTransferingWorkOrder)) else '' end) as [Sonraki Ýstasyon], P.GrossQuantity as [Brüt], P.NetQuantity as [Net] from Production P inner join Machine M on M.Oid = P.Machine inner join Station S on S.Oid = M.Station where P.GCRecord is null and CastTransferingWorkOrder is not null and P.ProductionDate between @begindate and @enddate) T group by [Ýstasyon], [Sonraki Ýstasyon] 
UNION 
select [Ýstasyon], [Sonraki Ýstasyon], SUM([Brüt]) as [Brüt], SUM([Net]) as [Net] from (select S.Code as [Ýstasyon], (case when P.BalloonFilmingWorkOrder is not null then (select Name from Station where Oid = (select NextStation from BalloonFilmingWorkOrder where Oid = P.BalloonFilmingWorkOrder)) else '' end) as [Sonraki Ýstasyon], P.GrossQuantity as [Brüt], P.NetQuantity as [Net] from Production P inner join Machine M on M.Oid = P.Machine inner join Station S on S.Oid = M.Station where P.GCRecord is null and BalloonFilmingWorkOrder is not null and P.ProductionDate between @begindate and @enddate) T group by [Ýstasyon], [Sonraki Ýstasyon] 
UNION 
select [Ýstasyon], [Sonraki Ýstasyon], SUM([Brüt]) as [Brüt], SUM([Net]) as [Net] from (select S.Code as [Ýstasyon], (case when P.PrintingWorkOrder is not null then (select Name from Station where Oid = (select NextStation from PrintingWorkOrder where Oid = P.PrintingWorkOrder)) else '' end) as [Sonraki Ýstasyon], P.GrossQuantity as [Brüt], P.NetQuantity as [Net] from Production P inner join Machine M on M.Oid = P.Machine inner join Station S on S.Oid = M.Station where P.GCRecord is null and PrintingWorkOrder is not null and P.ProductionDate between @begindate and @enddate) T group by [Ýstasyon], [Sonraki Ýstasyon] 
UNION 
select [Ýstasyon], [Sonraki Ýstasyon], SUM([Brüt]) as [Brüt], SUM([Net]) as [Net] from (select S.Code as [Ýstasyon], (case when P.LaminationWorkOrder is not null then (select Name from Station where Oid = (select NextStation from LaminationWorkOrder where Oid = P.LaminationWorkOrder)) else '' end) as [Sonraki Ýstasyon], P.GrossQuantity as [Brüt], P.NetQuantity as [Net] from Production P inner join Machine M on M.Oid = P.Machine inner join Station S on S.Oid = M.Station where P.GCRecord is null and LaminationWorkOrder is not null and P.ProductionDate between @begindate and @enddate) T group by [Ýstasyon], [Sonraki Ýstasyon] 
UNION 
select [Ýstasyon], [Sonraki Ýstasyon], SUM([Brüt]) as [Brüt], SUM([Net]) as [Net] from (select S.Code as [Ýstasyon], (case when P.SlicingWorkOrder is not null then (select Name from Station where Oid = (select NextStation from SlicingWorkOrder where Oid = P.SlicingWorkOrder)) else '' end) as [Sonraki Ýstasyon], P.GrossQuantity as [Brüt], P.NetQuantity as [Net] from Production P inner join Machine M on M.Oid = P.Machine inner join Station S on S.Oid = M.Station where P.GCRecord is null and SlicingWorkOrder is not null and P.ProductionDate between @begindate and @enddate) T group by [Ýstasyon], [Sonraki Ýstasyon] 
UNION 
select [Ýstasyon], [Sonraki Ýstasyon], SUM([Brüt]) as [Brüt], SUM([Net]) as [Net] from (select S.Code as [Ýstasyon], (case when P.CastSlicingWorkOrder is not null then (select Name from Station where Oid = (select NextStation from CastSlicingWorkOrder where Oid = P.CastSlicingWorkOrder)) else '' end) as [Sonraki Ýstasyon], P.GrossQuantity as [Brüt], P.NetQuantity as [Net] from Production P inner join Machine M on M.Oid = P.Machine inner join Station S on S.Oid = M.Station where P.GCRecord is null and CastSlicingWorkOrder is not null and P.ProductionDate between @begindate and @enddate) T group by [Ýstasyon], [Sonraki Ýstasyon] 
UNION 
select [Ýstasyon], [Sonraki Ýstasyon], SUM([Brüt]) as [Brüt], SUM([Net]) as [Net] from (select S.Code as [Ýstasyon], (case when P.CuttingWorkOrder is not null then (select Name from Station where Oid = (select NextStation from CuttingWorkOrder where Oid = P.CuttingWorkOrder)) else '' end) as [Sonraki Ýstasyon], P.GrossQuantity as [Brüt], P.NetQuantity as [Net] from Production P inner join Machine M on M.Oid = P.Machine inner join Station S on S.Oid = M.Station where P.GCRecord is null and CuttingWorkOrder is not null and P.ProductionDate between @begindate and @enddate) T group by [Ýstasyon], [Sonraki Ýstasyon] 
UNION 
select [Ýstasyon], [Sonraki Ýstasyon], SUM([Brüt]) as [Brüt], SUM([Net]) as [Net] from (select S.Code as [Ýstasyon], (case when P.RegeneratedWorkOrder is not null then (select Name from Station where Oid = (select NextStation from RegeneratedWorkOrder where Oid = P.RegeneratedWorkOrder)) else '' end) as [Sonraki Ýstasyon], P.GrossQuantity as [Brüt], P.NetQuantity as [Net] from Production P inner join Machine M on M.Oid = P.Machine inner join Station S on S.Oid = M.Station where P.GCRecord is null and RegeneratedWorkOrder is not null and P.ProductionDate between @begindate and @enddate) T group by [Ýstasyon], [Sonraki Ýstasyon] 
UNION 
select [Ýstasyon], [Sonraki Ýstasyon], SUM([Brüt]) as [Brüt], SUM([Net]) as [Net] from (select S.Code as [Ýstasyon], (case when P.CastRegeneratedWorkOrder is not null then (select Name from Station where Oid = (select NextStation from CastRegeneratedWorkOrder where Oid = P.CastRegeneratedWorkOrder)) else '' end) as [Sonraki Ýstasyon], P.GrossQuantity as [Brüt], P.NetQuantity as [Net] from Production P inner join Machine M on M.Oid = P.Machine inner join Station S on S.Oid = M.Station where P.GCRecord is null and CastRegeneratedWorkOrder is not null and P.ProductionDate between @begindate and @enddate) T group by [Ýstasyon], [Sonraki Ýstasyon] 
UNION 
select [Ýstasyon], [Sonraki Ýstasyon], SUM([Brüt]) as [Brüt], SUM([Net]) as [Net] from (select S.Code as [Ýstasyon], (case when P.Eco6WorkOrder is not null then (select Name from Station where Oid = (select NextStation from Eco6WorkOrder where Oid = P.Eco6WorkOrder)) else '' end) as [Sonraki Ýstasyon], P.GrossQuantity as [Brüt], P.NetQuantity as [Net] from Production P inner join Machine M on M.Oid = P.Machine inner join Station S on S.Oid = M.Station where P.GCRecord is null and Eco6WorkOrder is not null and P.ProductionDate between @begindate and @enddate) T group by [Ýstasyon], [Sonraki Ýstasyon] 
UNION 
select [Ýstasyon], [Sonraki Ýstasyon], SUM([Brüt]) as [Brüt], SUM([Net]) as [Net] from (select S.Code as [Ýstasyon], (case when P.Eco6CuttingWorkOrder is not null then (select Name from Station where Oid = (select NextStation from Eco6CuttingWorkOrder where Oid = P.Eco6CuttingWorkOrder)) else '' end) as [Sonraki Ýstasyon], P.GrossQuantity as [Brüt], P.NetQuantity as [Net] from Production P inner join Machine M on M.Oid = P.Machine inner join Station S on S.Oid = M.Station where P.GCRecord is null and Eco6CuttingWorkOrder is not null and P.ProductionDate between @begindate and @enddate) T group by [Ýstasyon], [Sonraki Ýstasyon] UNION 
select [Ýstasyon], [Sonraki Ýstasyon], SUM([Brüt]) as [Brüt], SUM([Net]) as [Net] from (select S.Code as [Ýstasyon], (case when P.Eco6LaminationWorkOrder is not null then (select Name from Station where Oid = (select NextStation from Eco6LaminationWorkOrder where Oid = P.Eco6LaminationWorkOrder)) else '' end) as [Sonraki Ýstasyon], P.GrossQuantity as [Brüt], P.NetQuantity as [Net] from Production P inner join Machine M on M.Oid = P.Machine inner join Station S on S.Oid = M.Station where P.GCRecord is null and Eco6LaminationWorkOrder is not null and P.ProductionDate between @begindate and @enddate) T group by [Ýstasyon], [Sonraki Ýstasyon] order by [Ýstasyon], [Sonraki Ýstasyon]